language: generic 
sudo: required
services:
  - docker
  # need docker cli pre-installed

before_install:
  - docker build -t ckting0723/docker-react -f Dockerfile.dev .
  # image tag only used in travis CI

script:
  # - docker run ckting0723/docker-react npm run test -- --coverage
  - docker run -e CI=true ckting0723/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-452599655945" # S3 bucket (hard drive)
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

